AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket named scarface

Resources:
  ScarfaceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: scarface
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref ScarfaceS3Bucket
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt ScarfaceS3Bucket.Arn
