AWSTemplateFormatVersion: "2010-09-09"
Description: Create a new S3 bucket with a globally-unique name (safe for CloudFormation deployments).

Parameters:
  BucketNamePrefix:
    Type: String
    Default: scarface
    Description: Lowercase prefix for the bucket name (letters/numbers/hyphens only).
    AllowedPattern: "^[a-z0-9-]{3,40}$"
    ConstraintDescription: "Use 3-40 characters: lowercase letters, numbers, hyphens only."

Resources:
  ScarfaceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Unique bucket name: <prefix>-<accountid>-<region>
      BucketName: !Sub "${BucketNamePrefix}-${AWS::AccountId}-${AWS::Region}"

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      Tags:
        - Key: Project
          Value: Scarface
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref ScarfaceS3Bucket

  BucketArn:
    Description: The ARN of the created S3 bucket
    Value: !GetAtt ScarfaceS3Bucket.Arn
